#!/bin/bash
# Install openstack-selinux if it is available
# dib-lint: disable=sete
set -ux
set -o pipefail

HAS_PACKAGE=$(yum list | grep python-futures)
if [ -n "$HAS_PACKAGE" ]; then
    install-packages python-futures
fi
